"""Compilation pipeline, deterministic optimization passes, and output writer."""

from __future__ import annotations

import hashlib
import json
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Set, Tuple

from . import __version__
from .adapters import adapt_frontmatter, source_invocation_policy
from .errors import SkillCompilerError
from .frontmatter import render_frontmatter, scalar_value
from .hook_optimizer import expected_extracted_section, optimize_extension_hooks
from .model import CompiledPackage, InvocationPolicy, Section, SkillIR
from .parser import parse_skill


@dataclass(frozen=True)
class CompileOptions:
    target: str
    extract_sections: Tuple[str, ...] = ()
    optimize_extension_hooks: bool = False
    invocation: str = "source"
    source_id: Optional[str] = None
    max_root_tokens: Optional[int] = None
    max_normal_path_tokens: Optional[int] = None


def compile_skill(source: Path, options: CompileOptions) -> CompiledPackage:
    """Compile one canonical skill into a harness-specific package."""

    ir = parse_skill(Path(source), source_id=options.source_id)
    target = options.target.lower()
    policy = _resolve_invocation(ir, options.invocation)
    adapted = adapt_frontmatter(ir, target, policy)
    body, references, extraction_transforms = _extract_sections(
        ir, options.extract_sections
    )
    scripts: Dict[str, str] = {}
    hook_transforms: List[Dict[str, object]] = []
    conditional_references: Set[str] = set()
    if options.optimize_extension_hooks:
        (
            body,
            references,
            scripts,
            hook_transforms,
            conditional_references,
        ) = optimize_extension_hooks(ir, body, references, target)

    generated_note = "<!-- Generated by Harnessmith; see .harnessmith.json. -->\n\n"
    root_text = render_frontmatter(adapted.fields) + "\n" + generated_note + body.lstrip("\n")

    files: Dict[str, str] = {"SKILL.md": _ensure_final_newline(root_text)}
    files.update(adapted.extra_files)
    files.update(references)
    files.update(scripts)

    transformations = adapted.transformations + extraction_transforms + hook_transforms
    metrics = _metrics(
        ir.source_text,
        files["SKILL.md"],
        references,
        scripts,
        conditional_references,
    )
    _enforce_budgets(metrics, options)
    manifest = _build_manifest(ir, target, files, transformations, metrics)
    files[".harnessmith.json"] = json.dumps(
        manifest, indent=2, sort_keys=True, ensure_ascii=False
    ) + "\n"

    name = scalar_value(ir.field("name"))
    assert isinstance(name, str)
    package = CompiledPackage(
        skill_name=name,
        target=target,
        files=files,
        manifest=manifest,
        metrics=metrics,
        transformations=transformations,
    )
    verify_package(ir, package, options.extract_sections)
    return package


def write_package(package: CompiledPackage, output: Path) -> None:
    """Write a package, replacing only files from an earlier compiler run."""

    output = Path(output)
    if output.exists():
        manifest_path = output / ".harnessmith.json"
        existing_entries = list(output.iterdir())
        if existing_entries and not manifest_path.is_file():
            raise SkillCompilerError(
                "refusing to overwrite non-compiler output directory: %s" % output
            )
        if manifest_path.is_file():
            try:
                old_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
                if old_manifest.get("compiler", {}).get("name") != "harnessmith":
                    raise SkillCompilerError("existing manifest has a different owner")
                file_hashes = old_manifest.get("files")
                if not isinstance(file_hashes, dict) or not all(
                    isinstance(path, str) for path in file_hashes
                ):
                    raise SkillCompilerError("existing manifest has an invalid files map")
                old_files = list(file_hashes.keys())
            except (OSError, ValueError, TypeError, AttributeError) as exc:
                raise SkillCompilerError(
                    "cannot safely read existing compiler manifest: %s" % exc
                ) from exc
            old_files.append(".harnessmith.json")
            candidates = [_safe_output_path(output, relative) for relative in old_files]
            for candidate in candidates:
                if candidate.is_file() or candidate.is_symlink():
                    candidate.unlink()
            _remove_empty_directories(output)

    output.mkdir(parents=True, exist_ok=True)
    for relative, content in sorted(package.files.items()):
        destination = _safe_output_path(output, relative)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")


def verify_package(
    ir: SkillIR, package: CompiledPackage, extracted_headings: Sequence[str]
) -> None:
    """Verify lossless section provenance and normative-statement retention."""

    combined = "\n".join(
        content
        for path, content in sorted(package.files.items())
        if path.endswith(".md")
    )
    source_normative = _normative_lines(ir.body)
    compiled_normative = _normative_lines(combined)
    missing = []
    for line in source_normative:
        if compiled_normative.count(line) < source_normative.count(line):
            missing.append(line)
    if missing:
        raise SkillCompilerError(
            "compiled package lost normative statements: %s" % "; ".join(sorted(set(missing)))
        )

    for heading in extracted_headings:
        section = _unique_section(ir, heading)
        transform = next(
            (
                item
                for item in package.transformations
                if item.get("type") == "extract-section"
                and item.get("heading") == heading
            ),
            None,
        )
        if transform is None:
            raise SkillCompilerError("missing provenance for extracted section: %s" % heading)
        output_path = str(transform["output"])
        output = package.files.get(output_path, "")
        source_section = _ensure_final_newline(section.text)
        expected_section = _ensure_final_newline(
            expected_extracted_section(ir, section)
        )
        if source_section not in output and expected_section not in output:
            raise SkillCompilerError(
                "reference does not contain exact source section: %s" % heading
            )

    for transform in package.transformations:
        if transform.get("type") != "resolve-extension-hooks":
            continue
        source_lines = transform.get("source_lines")
        source_sha256 = transform.get("source_sha256")
        fallback = str(transform.get("fallback"))
        matches = [
            section
            for section in ir.sections
            if [section.start_line, section.end_line] == source_lines
            and hashlib.sha256(section.text.encode("utf-8")).hexdigest()
            == source_sha256
        ]
        if len(matches) != 1 or _ensure_final_newline(
            matches[0].text
        ) not in package.files.get(fallback, ""):
            raise SkillCompilerError(
                "hook optimization lost its exact fallback contract: %s"
                % transform.get("event")
            )

    selected_sections = [_unique_section(ir, heading) for heading in extracted_headings]
    expected_root_headings = []
    for section in ir.sections:
        hidden_by_reference = any(
            selected.start_offset < section.start_offset < selected.end_offset
            for selected in selected_sections
        )
        if not hidden_by_reference:
            expected_root_headings.append(
                "%s %s" % ("#" * section.level, section.heading)
            )
    cursor = 0
    root = package.files["SKILL.md"]
    for heading_line in expected_root_headings:
        position = root.find(heading_line, cursor)
        if position < 0:
            raise SkillCompilerError(
                "compiled root lost or reordered orchestration heading: %s"
                % heading_line
            )
        cursor = position + len(heading_line)


def _resolve_invocation(ir: SkillIR, requested: str) -> InvocationPolicy:
    requested = requested.lower()
    if requested == "source":
        return source_invocation_policy(ir)
    if requested == "explicit":
        return InvocationPolicy(allow_model=False, allow_user=True)
    if requested == "automatic":
        return InvocationPolicy(allow_model=True, allow_user=True)
    raise SkillCompilerError("unknown invocation policy: %s" % requested)


def _extract_sections(
    ir: SkillIR, headings: Sequence[str]
) -> Tuple[str, Dict[str, str], List[Dict[str, object]]]:
    if len(set(headings)) != len(headings):
        raise SkillCompilerError("duplicate --extract-section selector")

    selected = [_unique_section(ir, heading) for heading in headings]
    for left in selected:
        for right in selected:
            if left is right:
                continue
            if left.start_offset <= right.start_offset < left.end_offset:
                raise SkillCompilerError(
                    "cannot extract nested sections together: '%s' contains '%s'"
                    % (left.heading, right.heading)
                )

    references: Dict[str, str] = {}
    transforms: List[Dict[str, object]] = []
    body = ir.body
    for section in sorted(selected, key=lambda item: item.start_offset, reverse=True):
        filename = "references/%s.md" % _section_slug(section.heading)
        if filename in references:
            raise SkillCompilerError(
                "extracted section filenames collide at: %s" % filename
            )
        heading_line = section.text.splitlines(keepends=True)[0]
        directive = (
            heading_line
            + "\n"
            + (
                "**Before this stage:** Read [`%s`](%s) completely; it remains "
                "authoritative. Do not continue until it is loaded.\n\n"
                % (filename, filename)
            )
        )
        body = body[: section.start_offset] + directive + body[section.end_offset :]

        note = "<!-- Generated by Harnessmith; see ../.harnessmith.json. -->\n\n"
        references[filename] = _ensure_final_newline(note + section.text)
        transforms.append(
            {
                "type": "extract-section",
                "heading": section.heading,
                "source_lines": [section.start_line, section.end_line],
                "source_sha256": hashlib.sha256(
                    section.text.encode("utf-8")
                ).hexdigest(),
                "output": filename,
            }
        )

    transforms.sort(key=lambda item: item.get("source_lines", [0])[0])
    return body, references, transforms


def _unique_section(ir: SkillIR, heading: str) -> Section:
    matches = [section for section in ir.sections if section.heading == heading]
    if not matches:
        available = ", ".join(section.heading for section in ir.sections)
        raise SkillCompilerError(
            "section '%s' not found; available headings: %s" % (heading, available)
        )
    if len(matches) > 1:
        raise SkillCompilerError(
            "section selector '%s' is ambiguous; heading occurs %d times"
            % (heading, len(matches))
        )
    return matches[0]


def _section_slug(heading: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", heading.lower()).strip("-")
    if not slug:
        raise SkillCompilerError("section heading cannot produce a reference filename")
    return slug


def _metrics(
    source: str,
    root: str,
    references: Dict[str, str],
    scripts: Dict[str, str],
    conditional_references: Set[str],
) -> Dict[str, int]:
    reference_chars = sum(len(value) for value in references.values())
    conditional_chars = sum(
        len(value)
        for path, value in references.items()
        if path in conditional_references
    )
    mandatory_chars = reference_chars - conditional_chars
    normal_path_chars = len(root) + mandatory_chars
    packaged_instruction_chars = len(root) + reference_chars
    script_chars = sum(len(value) for value in scripts.values())
    return {
        "source_skill_chars": len(source),
        "source_skill_token_estimate": _token_estimate(source),
        "compiled_root_chars": len(root),
        "compiled_root_token_estimate": _token_estimate(root),
        "reference_chars": reference_chars,
        "reference_token_estimate": sum(_token_estimate(value) for value in references.values()),
        "mandatory_reference_chars": mandatory_chars,
        "mandatory_reference_token_estimate": _token_estimate(
            "".join(
                value
                for path, value in references.items()
                if path not in conditional_references
            )
        ),
        "conditional_reference_chars": conditional_chars,
        "conditional_reference_token_estimate": _token_estimate(
            "".join(
                value
                for path, value in references.items()
                if path in conditional_references
            )
        ),
        "script_chars": script_chars,
        "script_token_estimate": _token_estimate("".join(scripts.values())),
        "normal_path_instruction_chars": normal_path_chars,
        "normal_path_instruction_token_estimate": _token_estimate(
            root
            + "".join(
                value
                for path, value in references.items()
                if path not in conditional_references
            )
        ),
        "normal_path_reduction_percent": round(
            (1 - normal_path_chars / len(source)) * 100
        )
        if source
        else 0,
        "packaged_instruction_chars": packaged_instruction_chars,
        "packaged_instruction_token_estimate": _token_estimate(
            root + "".join(references.values())
        ),
        "root_char_reduction": len(source) - len(root),
        "root_reduction_percent": round((1 - len(root) / len(source)) * 100) if source else 0,
    }


def _token_estimate(text: str) -> int:
    """Use a deterministic, explicitly approximate four-characters/token metric."""

    return int(math.ceil(len(text) / 4.0))


def _enforce_budgets(metrics: Dict[str, int], options: CompileOptions) -> None:
    budgets = (
        ("root", options.max_root_tokens, "compiled_root_token_estimate"),
        (
            "normal path",
            options.max_normal_path_tokens,
            "normal_path_instruction_token_estimate",
        ),
    )
    for label, limit, metric in budgets:
        if limit is None:
            continue
        if limit < 1:
            raise SkillCompilerError("%s token budget must be positive" % label)
        actual = metrics[metric]
        if actual > limit:
            raise SkillCompilerError(
                "%s token budget exceeded: %d > %d" % (label, actual, limit)
            )


def _build_manifest(
    ir: SkillIR,
    target: str,
    files: Dict[str, str],
    transformations: List[Dict[str, object]],
    metrics: Dict[str, int],
) -> Dict[str, object]:
    return {
        "schema_version": 1,
        "compiler": {"name": "harnessmith", "version": __version__},
        "target": target,
        "source": {
            "path": ir.source_id,
            "sha256": ir.source_sha256,
        },
        "transformations": transformations,
        "metrics": metrics,
        "files": {
            path: hashlib.sha256(content.encode("utf-8")).hexdigest()
            for path, content in sorted(files.items())
        },
    }


def _normative_lines(text: str) -> List[str]:
    marker = re.compile(
        r"\b(MUST(?:\s+NOT)?|NEVER|REQUIRED|STRICTLY|IMPORTANT|ABORT|STOP|WAIT)\b|\b[Dd]o not\b"
    )
    return [
        re.sub(r"\s+", " ", line.strip())
        for line in text.splitlines()
        if marker.search(line)
    ]


def _safe_output_path(root: Path, relative: str) -> Path:
    path = Path(relative)
    if path.is_absolute() or ".." in path.parts:
        raise SkillCompilerError("unsafe generated output path: %s" % relative)
    return root / path


def _remove_empty_directories(root: Path) -> None:
    directories = sorted(
        (path for path in root.rglob("*") if path.is_dir()),
        key=lambda path: len(path.parts),
        reverse=True,
    )
    for directory in directories:
        try:
            directory.rmdir()
        except OSError:
            pass


def _ensure_final_newline(text: str) -> str:
    return text.rstrip("\n") + "\n"
