"""Compilation pipeline, deterministic optimization passes, and output writer."""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Mapping, Optional, Sequence, Set, Tuple

from . import __version__
from .adapters import adapt_frontmatter, source_invocation_policy
from .errors import SkillCompilerError
from .frontmatter import render_frontmatter, scalar_value
from .hook_optimizer import expected_extracted_section, optimize_extension_hooks
from .manifest import is_safe_relative_path, require_valid_manifest
from .metrics import estimate_tokens
from .model import CompiledPackage, InvocationPolicy, SkillIR
from .parser import parse_skill
from .transforms import ExtractSectionsTransform, resolve_section


@dataclass(frozen=True)
class CompileOptions:
    target: str
    extract_sections: Tuple[str, ...] = ()
    optimize_extension_hooks: bool = False
    invocation: str = "source"
    source_id: Optional[str] = None
    max_root_tokens: Optional[int] = None
    max_normal_path_tokens: Optional[int] = None
    expected_source_sha256: Optional[str] = None
    recipe_id: Optional[str] = None
    recipe_sha256: Optional[str] = None


def compile_skill(source: Path, options: CompileOptions) -> CompiledPackage:
    """Compile one canonical skill into a harness-specific package."""

    ir = parse_skill(Path(source), source_id=options.source_id)
    if (
        options.expected_source_sha256 is not None
        and ir.source_sha256 != options.expected_source_sha256
    ):
        raise SkillCompilerError(
            "source hash changed: recipe expects %s, got %s; re-audit before compiling"
            % (options.expected_source_sha256, ir.source_sha256)
        )
    target = options.target.lower()
    policy = _resolve_invocation(ir, options.invocation)
    adapted = adapt_frontmatter(ir, target, policy)
    (
        bundled_text,
        bundled_binary,
        executable_files,
        resource_transforms,
    ) = _load_bundled_resources(ir.source_path.parent)
    extraction = ExtractSectionsTransform(options.extract_sections)
    extraction_analysis = extraction.analyze(ir)
    extraction_result = extraction.apply(ir, extraction_analysis)
    extraction.verify(ir, extraction_analysis, extraction_result)
    body = extraction_result.body
    references = extraction_result.references
    extraction_transforms = extraction_result.transformations
    scripts: Dict[str, str] = {}
    hook_transforms: List[Dict[str, object]] = []
    conditional_references: Set[str] = set()
    if options.optimize_extension_hooks:
        (
            body,
            references,
            scripts,
            hook_transforms,
            conditional_references,
        ) = optimize_extension_hooks(ir, body, references, target)

    generated_note = "<!-- Generated by Harnessmith; see .harnessmith.json. -->\n\n"
    root_text = render_frontmatter(adapted.fields) + "\n" + generated_note + body.lstrip("\n")

    files: Dict[str, str] = {"SKILL.md": _ensure_final_newline(root_text)}
    _merge_text_files(files, bundled_text)
    _merge_text_files(files, adapted.extra_files)
    _merge_text_files(files, references)
    _merge_text_files(files, scripts)
    binary_files = dict(bundled_binary)
    collisions = set(files).intersection(binary_files)
    if collisions:
        raise SkillCompilerError(
            "generated output collides with bundled resource: %s"
            % ", ".join(sorted(collisions))
        )

    transformations = (
        adapted.transformations
        + resource_transforms
        + extraction_transforms
        + hook_transforms
    )
    all_references = {
        path: content
        for path, content in files.items()
        if path.startswith("references/")
    }
    all_scripts = {
        path: content for path, content in files.items() if path.startswith("scripts/")
    }
    mandatory_references = {
        str(item["output"])
        for item in extraction_transforms
        if isinstance(item.get("output"), str)
    } - conditional_references
    metrics = _metrics(
        ir.source_text,
        files["SKILL.md"],
        all_references,
        all_scripts,
        mandatory_references,
        conditional_references,
    )
    _enforce_budgets(metrics, options)
    manifest = _build_manifest(
        ir,
        target,
        files,
        binary_files,
        transformations,
        metrics,
        executable_files,
        options,
    )
    files[".harnessmith.json"] = json.dumps(
        manifest, indent=2, sort_keys=True, ensure_ascii=False
    ) + "\n"

    name = scalar_value(ir.field("name"))
    assert isinstance(name, str)
    package = CompiledPackage(
        skill_name=name,
        target=target,
        files=files,
        manifest=manifest,
        metrics=metrics,
        transformations=transformations,
        binary_files=binary_files,
        executable_files=executable_files,
    )
    verify_package(ir, package, options.extract_sections)
    return package


def write_package(package: CompiledPackage, output: Path) -> None:
    """Transactionally replace compiler-owned files in an output directory."""

    output = Path(output)
    if output.is_symlink():
        raise SkillCompilerError("refusing to write through symlinked output: %s" % output)
    if output.exists() and not output.is_dir():
        raise SkillCompilerError("output exists and is not a directory: %s" % output)

    package_bytes = dict(package.file_bytes())
    _validate_compiled_package_bytes(package, package_bytes)
    old_files: List[str] = []
    if output.exists():
        manifest_path = output / ".harnessmith.json"
        existing_entries = list(output.iterdir())
        if existing_entries and not manifest_path.is_file():
            raise SkillCompilerError(
                "refusing to overwrite non-compiler output directory: %s" % output
            )
        if manifest_path.is_file():
            try:
                old_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
                owned = require_valid_manifest(old_manifest)
                file_hashes = owned["files"]
                assert isinstance(file_hashes, dict)
                old_files = list(file_hashes)
                _verify_owned_output_hashes(output, file_hashes)
            except (OSError, ValueError, TypeError, AttributeError) as exc:
                raise SkillCompilerError(
                    "cannot safely read existing compiler manifest: %s" % exc
                ) from exc
            old_files.append(".harnessmith.json")

        old_owned = set(old_files)
        for relative in package_bytes:
            destination = _safe_output_path(output, relative)
            if (
                relative not in old_owned
                and (destination.exists() or destination.is_symlink())
            ):
                raise SkillCompilerError(
                    "generated output path collides with an unowned file: %s"
                    % relative
                )

    output.parent.mkdir(parents=True, exist_ok=True)
    workspace = Path(
        tempfile.mkdtemp(prefix=".%s.harnessmith-" % output.name, dir=output.parent)
    )
    staged = workspace / "package"
    backup = workspace / "previous"
    replaced = False
    cleanup_workspace = True
    try:
        if output.exists():
            shutil.copytree(output, staged, symlinks=True)
        else:
            staged.mkdir()
        for relative in old_files:
            candidate = _safe_output_path(staged, relative)
            if candidate.is_file() or candidate.is_symlink():
                candidate.unlink()
        _remove_empty_directories(staged)

        ordered = sorted(path for path in package_bytes if path != ".harnessmith.json")
        ordered.append(".harnessmith.json")
        for relative in ordered:
            destination = _safe_output_path(staged, relative)
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(package_bytes[relative])
            destination.chmod(
                0o755 if relative in package.executable_files else 0o644
            )

        try:
            if output.exists():
                replaced = True
                os.replace(output, backup)
            os.replace(staged, output)
        except BaseException:
            if replaced and backup.exists() and not output.exists():
                try:
                    os.replace(backup, output)
                except OSError as rollback_error:
                    cleanup_workspace = False
                    raise SkillCompilerError(
                        "package publish and rollback failed; previous output remains at %s"
                        % backup
                    ) from rollback_error
            raise
    finally:
        if cleanup_workspace:
            shutil.rmtree(workspace, ignore_errors=True)


def verify_package(
    ir: SkillIR, package: CompiledPackage, extracted_headings: Sequence[str]
) -> None:
    """Verify lossless section provenance and normative-statement retention."""

    combined = "\n".join(
        content
        for path, content in sorted(package.files.items())
        if path.endswith(".md")
    )
    source_normative = _normative_lines(ir.body)
    compiled_normative = _normative_lines(combined)
    missing = []
    for line in source_normative:
        if compiled_normative.count(line) < source_normative.count(line):
            missing.append(line)
    if missing:
        raise SkillCompilerError(
            "compiled package lost normative statements: %s" % "; ".join(sorted(set(missing)))
        )

    for heading in extracted_headings:
        section = resolve_section(ir, heading)
        transform = next(
            (
                item
                for item in package.transformations
                if item.get("type") == "extract-section"
                and item.get("section_id") == section.identity
            ),
            None,
        )
        if transform is None:
            raise SkillCompilerError("missing provenance for extracted section: %s" % heading)
        output_path = str(transform["output"])
        output = package.files.get(output_path, "")
        source_section = _ensure_final_newline(section.text)
        expected_section = _ensure_final_newline(
            expected_extracted_section(ir, section)
        )
        if source_section not in output and expected_section not in output:
            raise SkillCompilerError(
                "reference does not contain exact source section: %s" % heading
            )

    for transform in package.transformations:
        if transform.get("type") != "resolve-extension-hooks":
            continue
        source_lines = transform.get("source_lines")
        source_sha256 = transform.get("source_sha256")
        fallback = str(transform.get("fallback"))
        matches = [
            section
            for section in ir.sections
            if [section.start_line, section.end_line] == source_lines
            and hashlib.sha256(section.text.encode("utf-8")).hexdigest()
            == source_sha256
        ]
        if len(matches) != 1 or _ensure_final_newline(
            matches[0].text
        ) not in package.files.get(fallback, ""):
            raise SkillCompilerError(
                "hook optimization lost its exact fallback contract: %s"
                % transform.get("event")
            )

    selected_sections = [resolve_section(ir, heading) for heading in extracted_headings]
    expected_root_headings = []
    for section in ir.sections:
        hidden_by_reference = any(
            selected.start_offset < section.start_offset < selected.end_offset
            for selected in selected_sections
        )
        if not hidden_by_reference:
            expected_root_headings.append(section.heading_text.rstrip("\r\n"))
    cursor = 0
    root = package.files["SKILL.md"]
    for heading_line in expected_root_headings:
        position = root.find(heading_line, cursor)
        if position < 0:
            raise SkillCompilerError(
                "compiled root lost or reordered orchestration heading: %s"
                % heading_line
            )
        cursor = position + len(heading_line)


def _resolve_invocation(ir: SkillIR, requested: str) -> InvocationPolicy:
    requested = requested.lower()
    if requested == "source":
        return source_invocation_policy(ir)
    if requested == "explicit":
        return InvocationPolicy(allow_model=False, allow_user=True)
    if requested == "automatic":
        return InvocationPolicy(allow_model=True, allow_user=True)
    raise SkillCompilerError("unknown invocation policy: %s" % requested)


def _metrics(
    source: str,
    root: str,
    references: Dict[str, str],
    scripts: Dict[str, str],
    mandatory_references: Set[str],
    conditional_references: Set[str],
) -> Dict[str, int]:
    reference_chars = sum(len(value) for value in references.values())
    conditional_chars = sum(
        len(value)
        for path, value in references.items()
        if path in conditional_references
    )
    mandatory_chars = sum(
        len(value)
        for path, value in references.items()
        if path in mandatory_references
    )
    normal_path_chars = len(root) + mandatory_chars
    packaged_instruction_chars = len(root) + reference_chars
    script_chars = sum(len(value) for value in scripts.values())
    return {
        "source_skill_chars": len(source),
        "source_skill_token_estimate": estimate_tokens(source),
        "compiled_root_chars": len(root),
        "compiled_root_token_estimate": estimate_tokens(root),
        "reference_chars": reference_chars,
        "reference_token_estimate": sum(
            estimate_tokens(value) for value in references.values()
        ),
        "mandatory_reference_chars": mandatory_chars,
        "mandatory_reference_token_estimate": estimate_tokens(
            "".join(
                value
                for path, value in references.items()
                if path in mandatory_references
            )
        ),
        "conditional_reference_chars": conditional_chars,
        "conditional_reference_token_estimate": estimate_tokens(
            "".join(
                value
                for path, value in references.items()
                if path in conditional_references
            )
        ),
        "script_chars": script_chars,
        "script_token_estimate": estimate_tokens("".join(scripts.values())),
        "normal_path_instruction_chars": normal_path_chars,
        "normal_path_instruction_token_estimate": estimate_tokens(
            root
            + "".join(
                value
                for path, value in references.items()
                if path in mandatory_references
            )
        ),
        "normal_path_reduction_percent": round(
            (1 - normal_path_chars / len(source)) * 100
        )
        if source
        else 0,
        "packaged_instruction_chars": packaged_instruction_chars,
        "packaged_instruction_token_estimate": estimate_tokens(
            root + "".join(references.values())
        ),
        "root_char_reduction": len(source) - len(root),
        "root_reduction_percent": round((1 - len(root) / len(source)) * 100) if source else 0,
    }


def _enforce_budgets(metrics: Dict[str, int], options: CompileOptions) -> None:
    budgets = (
        ("root", options.max_root_tokens, "compiled_root_token_estimate"),
        (
            "normal path",
            options.max_normal_path_tokens,
            "normal_path_instruction_token_estimate",
        ),
    )
    for label, limit, metric in budgets:
        if limit is None:
            continue
        if limit < 1:
            raise SkillCompilerError("%s token budget must be positive" % label)
        actual = metrics[metric]
        if actual > limit:
            raise SkillCompilerError(
                "%s token budget exceeded: %d > %d" % (label, actual, limit)
            )


def _build_manifest(
    ir: SkillIR,
    target: str,
    files: Dict[str, str],
    binary_files: Dict[str, bytes],
    transformations: List[Dict[str, object]],
    metrics: Dict[str, int],
    executable_files: Tuple[str, ...],
    options: CompileOptions,
) -> Dict[str, object]:
    file_bytes = {path: content.encode("utf-8") for path, content in files.items()}
    file_bytes.update(binary_files)
    manifest: Dict[str, object] = {
        "schema_version": 1,
        "compiler": {"name": "harnessmith", "version": __version__},
        "target": target,
        "source": {
            "path": ir.source_id,
            "sha256": ir.source_sha256,
        },
        "transformations": transformations,
        "metrics": metrics,
        "files": {
            path: hashlib.sha256(content).hexdigest()
            for path, content in sorted(file_bytes.items())
        },
    }
    if executable_files:
        manifest["executables"] = list(executable_files)
    if options.recipe_id is not None:
        manifest["recipe"] = {
            "path": options.recipe_id,
            "sha256": options.recipe_sha256,
        }
    return manifest


def _normative_lines(text: str) -> List[str]:
    marker = re.compile(
        r"\b(MUST(?:\s+NOT)?|NEVER|REQUIRED|STRICTLY|IMPORTANT|ABORT|STOP|WAIT)\b|\b[Dd]o not\b"
    )
    return [
        re.sub(r"\s+", " ", line.strip())
        for line in text.splitlines()
        if marker.search(line)
    ]


def _safe_output_path(root: Path, relative: str) -> Path:
    if not is_safe_relative_path(relative):
        raise SkillCompilerError("unsafe generated output path: %s" % relative)
    path = Path(relative)
    destination = root / path
    if destination.is_symlink():
        raise SkillCompilerError("unsafe symlink in generated output path: %s" % relative)
    cursor = destination.parent
    while cursor != root.parent:
        if cursor.is_symlink():
            raise SkillCompilerError("unsafe symlink in generated output path: %s" % relative)
        if cursor == root:
            break
        cursor = cursor.parent
    return destination


def _remove_empty_directories(root: Path) -> None:
    directories = sorted(
        (path for path in root.rglob("*") if path.is_dir()),
        key=lambda path: len(path.parts),
        reverse=True,
    )
    for directory in directories:
        try:
            directory.rmdir()
        except OSError:
            pass


def _ensure_final_newline(text: str) -> str:
    return text.rstrip("\n") + "\n"


def _load_bundled_resources(
    skill_root: Path,
) -> Tuple[Dict[str, str], Dict[str, bytes], Tuple[str, ...], List[Dict[str, object]]]:
    text_files: Dict[str, str] = {}
    binary_files: Dict[str, bytes] = {}
    executables: List[str] = []
    transformations: List[Dict[str, object]] = []
    for directory_name in ("references", "scripts", "assets"):
        directory = skill_root / directory_name
        if not directory.exists():
            continue
        if directory.is_symlink() or not directory.is_dir():
            raise SkillCompilerError(
                "bundled resource directory is not a safe directory: %s" % directory
            )
        for path in sorted(directory.rglob("*")):
            relative = path.relative_to(skill_root).as_posix()
            if path.is_symlink():
                raise SkillCompilerError("bundled resource must not be a symlink: %s" % relative)
            if path.is_dir():
                continue
            if not path.is_file():
                raise SkillCompilerError("bundled resource is not a regular file: %s" % relative)
            content = path.read_bytes()
            try:
                text_files[relative] = content.decode("utf-8")
                kind = "text"
            except UnicodeDecodeError:
                binary_files[relative] = content
                kind = "binary"
            executable = bool(path.stat().st_mode & 0o111)
            if executable:
                executables.append(relative)
            transformations.append(
                {
                    "type": "preserve-resource",
                    "path": relative,
                    "content": kind,
                    "source_sha256": hashlib.sha256(content).hexdigest(),
                    "executable": executable,
                }
            )
    return (
        text_files,
        binary_files,
        tuple(sorted(executables)),
        transformations,
    )


def _merge_text_files(destination: Dict[str, str], additions: Mapping[str, str]) -> None:
    collisions = set(destination).intersection(additions)
    if collisions:
        raise SkillCompilerError(
            "generated output path collides with existing package file: %s"
            % ", ".join(sorted(collisions))
        )
    destination.update(additions)


def _validate_compiled_package_bytes(
    package: CompiledPackage, package_bytes: Mapping[str, bytes]
) -> None:
    manifest = require_valid_manifest(package.manifest)
    manifest_content = package_bytes.get(".harnessmith.json")
    if manifest_content is None:
        raise SkillCompilerError("compiled package is missing .harnessmith.json")
    try:
        serialized = json.loads(manifest_content.decode("utf-8"))
    except (UnicodeError, ValueError) as exc:
        raise SkillCompilerError("compiled package manifest is unreadable: %s" % exc) from exc
    if serialized != manifest:
        raise SkillCompilerError("compiled package manifest content does not match metadata")
    file_hashes = manifest["files"]
    assert isinstance(file_hashes, dict)
    actual_paths = set(package_bytes) - {".harnessmith.json"}
    if actual_paths != set(file_hashes):
        raise SkillCompilerError("compiled package files do not match its manifest")
    for relative, expected in file_hashes.items():
        if not is_safe_relative_path(relative):
            raise SkillCompilerError("unsafe generated output path: %s" % relative)
        actual = hashlib.sha256(package_bytes[relative]).hexdigest()
        if actual != expected:
            raise SkillCompilerError("compiled package hash differs: %s" % relative)
    if tuple(sorted(package.executable_files)) != tuple(manifest.get("executables", [])):
        raise SkillCompilerError("compiled package executable metadata differs")


def _verify_owned_output_hashes(
    output: Path, file_hashes: Mapping[str, object]
) -> None:
    for relative, expected in file_hashes.items():
        if not isinstance(relative, str) or not is_safe_relative_path(relative):
            raise SkillCompilerError("unsafe generated output path: %r" % relative)
        path = _safe_output_path(output, relative)
        if path.is_symlink() or not path.is_file():
            raise SkillCompilerError(
                "existing compiler-owned file is missing or unsafe: %s" % relative
            )
        if hashlib.sha256(path.read_bytes()).hexdigest() != expected:
            raise SkillCompilerError(
                "existing compiler-owned file was modified: %s; verify or use a new output directory"
                % relative
            )
