"""Explicit, verifiable compiler transforms.

Transforms are intentionally small: analysis resolves all source selectors and
rejects unsafe plans; application changes text; verification proves the stated
lossless invariant against the produced files.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from typing import Dict, Generic, List, Protocol, Sequence, Tuple, TypeVar

from .errors import SkillCompilerError
from .model import Section, SkillIR


AnalysisT = TypeVar("AnalysisT")
ResultT = TypeVar("ResultT")


class Transform(Protocol, Generic[AnalysisT, ResultT]):
    """Protocol implemented by ordered compiler passes."""

    name: str
    classification: str

    def analyze(self, ir: SkillIR) -> AnalysisT: ...

    def apply(self, ir: SkillIR, analysis: AnalysisT) -> ResultT: ...

    def verify(self, ir: SkillIR, analysis: AnalysisT, result: ResultT) -> None: ...


@dataclass(frozen=True)
class ExtractionResult:
    body: str
    references: Dict[str, str]
    transformations: List[Dict[str, object]]


class ExtractSectionsTransform:
    """Losslessly move selected sections into mandatory reference files."""

    name = "extract-sections"
    classification = "lossless"

    def __init__(self, selectors: Sequence[str]) -> None:
        self.selectors = tuple(selectors)

    def analyze(self, ir: SkillIR) -> Tuple[Section, ...]:
        if len(set(self.selectors)) != len(self.selectors):
            raise SkillCompilerError("duplicate --extract-section selector")
        selected = tuple(resolve_section(ir, selector) for selector in self.selectors)
        for left in selected:
            for right in selected:
                if (
                    left is not right
                    and left.start_offset <= right.start_offset < left.end_offset
                ):
                    raise SkillCompilerError(
                        "cannot extract nested sections together: '%s' contains '%s'"
                        % (left.identity, right.identity)
                    )
        self._reject_cross_document_fragments(ir, selected)
        return selected

    def apply(self, ir: SkillIR, analysis: Tuple[Section, ...]) -> ExtractionResult:
        references: Dict[str, str] = {}
        transformations: List[Dict[str, object]] = []
        body = ir.body
        for section in sorted(analysis, key=lambda item: item.start_offset, reverse=True):
            filename = "references/%s.md" % section_slug(section)
            if filename in references:
                raise SkillCompilerError("extracted section filenames collide at: %s" % filename)
            directive = section.heading_text + "\n" + (
                "**Before this stage:** Read [`%s`](%s) completely; it remains "
                "authoritative. Do not continue until it is loaded.\n\n" % (filename, filename)
            )
            body = body[: section.start_offset] + directive + body[section.end_offset :]
            note = "<!-- Generated by Harnessmith; see ../.harnessmith.json. -->\n\n"
            references[filename] = ensure_final_newline(note + section.text)
            transformations.append(
                {
                    "type": "extract-section",
                    "heading": section.heading,
                    "section_id": section.identity,
                    "source_lines": [section.start_line, section.end_line],
                    "source_sha256": hashlib.sha256(
                        section.text.encode("utf-8")
                    ).hexdigest(),
                    "output": filename,
                }
            )
        transformations.sort(key=lambda item: item.get("source_lines", [0])[0])
        return ExtractionResult(body, references, transformations)

    def verify(
        self, ir: SkillIR, analysis: Tuple[Section, ...], result: ExtractionResult
    ) -> None:
        for section in analysis:
            record = next(
                (
                    item
                    for item in result.transformations
                    if item["section_id"] == section.identity
                ),
                None,
            )
            if record is None:
                raise SkillCompilerError(
                    "missing provenance for extracted section: %s" % section.identity
                )
            output = result.references.get(str(record["output"]), "")
            if ensure_final_newline(section.text) not in output:
                raise SkillCompilerError(
                    "reference does not contain exact source section: %s" % section.identity
                )

    @staticmethod
    def _reject_cross_document_fragments(
        ir: SkillIR, selected: Tuple[Section, ...]
    ) -> None:
        if not selected:
            return
        # Moving either endpoint makes a local `#fragment` link ambiguous. We do
        # not guess at rewritten anchors because renderer slug rules differ.
        fragment_link = re.compile(
            r"\]\(\s*#[^)\s]+(?:\s+[^)]*)?\)"
            r"|^ {0,3}\[[^\]]+\]:\s*#\S+"
            r'|\bhref\s*=\s*["\']#',
            re.IGNORECASE | re.MULTILINE,
        )
        if fragment_link.search(ir.body):
            raise SkillCompilerError(
                "cannot safely extract sections containing local fragment links; "
                "cross-document anchor rewriting requires review"
            )


_OCCURRENCE_SELECTOR = re.compile(r"^(.*)\[([1-9][0-9]*)\]$")


def resolve_section(ir: SkillIR, selector: str) -> Section:
    """Resolve `Heading` or stable duplicate selector `Heading[n]`."""

    exact = [section for section in ir.sections if section.heading == selector]
    if len(exact) == 1:
        return exact[0]
    if len(exact) > 1:
        choices = ", ".join(section.identity for section in exact)
        raise SkillCompilerError(
            "section selector '%s' is ambiguous; use one of: %s" % (selector, choices)
        )
    explicit = _OCCURRENCE_SELECTOR.match(selector)
    if explicit:
        heading, occurrence_text = explicit.groups()
        matches = [
            section
            for section in ir.sections
            if section.heading == heading and section.occurrence == int(occurrence_text)
        ]
        if len(matches) == 1:
            return matches[0]
    available = ", ".join(section.identity for section in ir.sections)
    raise SkillCompilerError(
        "section '%s' not found; available selectors: %s" % (selector, available)
    )


def section_slug(section: Section) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", section.heading.lower()).strip("-")
    if not slug:
        raise SkillCompilerError("section heading cannot produce a reference filename")
    if section.occurrence > 1:
        slug += "-%d" % section.occurrence
    return slug


def ensure_final_newline(text: str) -> str:
    return text.rstrip("\n") + "\n"
